### ISSUE TITLE
能加入更多兵种么？

### ISSUE THREAD

**Issue by majorcheng** [Asvel/tacticsogre#1]
因为用了ce修改， 可以使用敌方兵种，特别是174一个“未知” 兵种， 能使用所有的技能， 简介是地狱里的灵魂没有实体啥啥的， 能把他们都给加入到数据里面吗？

以及，中英文对照表， 能不能添加物品的内容~

**Comment by Asvel** [comment]
游戏流程中无法实际获取的内容对大部分玩家来说是垃圾信息，列出来占据不必要的注意力得不偿失，特殊需求可以考虑根据这个 [ImHex](https://imhex.werwolv.net/) pattern 自行取得数据：<https://github.com/Asvel/tacticsogre-datamining/blob/master/imhex-patterns/patterns/tacticsogre.xlce.hexpat#L51>。

道具我有考虑过，但是道具实在是太多了，篇幅比现在页面上所有的加起来还要多。

**Comment by Asvel** [comment]
我把道具的译名加上了，放到了单独的一页：<https://asvel.github.io/tacticsogre/translations-item>。

**Comment by tinunkai** [comment]
无敌
